### DISCUSSION TITLE
Example project published online

### DISCUSSION THREAD

**Discussion by pookieman** [Dilbert66/esphome-dsckeybus#150] [Q&A]
Hello!

First thanks to the author for putting all this together, instructions look great! I'm a software person so can deal with HASS/Esphome programming etc. Where I am more green is the wiring/soldering etc. So I was wondering if anyone knew of a youtube video or other blog where the step by step instructions for the wiring required for this project can be found? Namely taking the ESP32 and attaching the various resistors/transistors to the pins on the ESP32 and the DSC alarm? Even pictures would help.

For example what is an Isolated vs Non Isolated option?! :) again full of appreciation for folks that give their time away for these projects!

Cheers

**Comment by pookieman** [comment]
This probably isn't super useful but thought I'd share the progress on the breadboard

![WhatsApp Image 2024-12-01 at 21 30 26](https://github.com/user-attachments/assets/00495207-f202-488b-9614-7c1d7a36b09d)

**Comment by Dilbert66** [comment]
That design will work fine but it looks to be an ESP8266. I would recommend an ESP32.    If you want an even easier one to build, you can also try this one below.
This design  uses a 4 channel level converter such as this type. Comes under various names, etc.  You can them much cheaper then this one. https://a.co/d/eHbKzen
Here's a quick version using a Wemos ESP32 D1 MINI .  YOu can use any ESP32 you want.  On the esp32 side, using GPIO18 for the yellow (clock line) to LV1 and GPIO19 for the green (data line) to LV2 and black to GND (ground) , and 3.3 volt red to LV (low voltage).   On the HV side, GND goes to black of the DSC panel, HV1 to the yellow line of the dsc panel, HV2 goes to the data line of the panel.   

So for the ESPHOME yaml, config you would use for the pin config:
```
dscclockpin: 19
dscreadpin: 18
dscwritepin: 18
```
You can use any available pin you want, these are just examples.  Just make sure you change the YAML config to match.
This circuit is from the dev design, mosfet level convert version. https://github.com/Dilbert66/esphome-dsckeybus/tree/dev?tab=readme-ov-file
![dsccircuit](https://github.com/user-attachments/assets/f63c56b4-93d2-4ab1-b566-f3d75e99d509)


IMPORTANT: Make sure you use the "dev" branch version of the software for this version. It will not work with the "master" branch.

**Comment by pookieman** [comment]
Thank you.. I've made some progress.. got my circuit connected to the black, yellow and green wires where the extender is connected.. I am assume this ok? 

<img width="719" alt="image" src="https://github.com/user-attachments/assets/92f00e9e-d530-4a32-8e6b-e0fe46176439">

Once I plugged everything in .. the 2 panels on the wall started beeping and my wife freaked out 🙃

I unplugged the esp8266

Now I am wondering if I have the right values in the code 🤔

I have the following values .. 

#ESP8266 Pins
  dscclockpin: "1"
  dscreadpin: "2"
  dscwritepin: "2" 

I am basing my wiring on the example on this [page](https://github.com/Dilbert66/esphome-dsckeybus/tree/master?tab=readme-ov-file)  
![image](https://github.com/user-attachments/assets/79142bcd-9f84-41b3-bdb8-be727f3ae9d9)

Am I write is saying

Yellow (D1) line in is dscclockpin
Green (D2) line in is dscreadpin
Green (D2) line out is dscwritepin

that last one seems wrong .. in the example it looks like D8 is line out .. ? appreciate any help again

**Comment by Dilbert66** [comment]
Yes, d8 is line out (write pin) The green line is used for read and write but from different pins with that circuit.
The circuit you used above has different pins for all functions.  The other example I showed you , is  a completely different circuit and that one uses the same pins for read/write. Don't confuse the two.

**Reply by pookieman** [reply]
Thanks I'll try this out later .. appreciate the continued support.. 

Still have the "alarm" light lit up on the DSC wall panel.. got to figure out how to get rid of that too.. also

![image](https://github.com/user-attachments/assets/71a2710f-72f1-413a-9e58-1e9adc028574)

stupid question (probably) each one that says 'GND' needs to be connected back to ground? And I should be able ok to connect these back to the Black connection on the DSC extender? same of the green/yellow - they don't need to be connected back to the main motherboard on the wall?

**Reply by pookieman** [reply]
and I crossed out the 3V3 and 5V - because I'm using the microusb to power the esp2866

**Comment by Dilbert66** [comment]
Everything that says GND gets connected together and goes to the black line to the extender. Correct. Yes, you can connect to the extender yellow and green lines as well. It's the same bus.
You can clear the errors on the panel usually by going into *2 and viewing the messages. Exit with the # key.

**Reply by pookieman** [reply]
amazing .. thanks so much for the swift responses.. I'll try it out.. so excited about adding this to HASS and showing my spouse why it was worth me hunched over a work bench and cursing when trying to remember how to soldering .. that $100 I saved I'll send to the food bank!

**Comment by pookieman** [comment]
ooooof still struggling here :( 

when booting it goes into a loop:
```
[18:46:45][C][safe_mode:079]: There have been 3 suspected unsuccessful boot attempts
[18:46:45][I][app:029]: Running through setup()...
[18:46:54][D][binary_sensor:034]: 'Fr�
[18:46:54] ets Jan  8 2013,rst cause:4, boot mode:(3,6)
[18:46:54]
[18:46:54]wdt reset
[18:46:54]load 0x4010f000, len 3424, room 16 
[18:46:54]tail 0
[18:46:54]chksum 0x2e
[18:46:54]load 0x3fff20b8, len 40, room 8 
[18:46:54]tail 0
[18:46:54]chksum 0x2b
[18:46:54]csum 0x2b
[18:46:54]v000798d0
[18:46:54]~ld
[18:46:54][logger:034]: Log initialized
[18:46:54][C][safe_mode:079]: There have been 4 suspected unsuccessful boot attempts
[18:46:54][I][app:029]: Running through setup()...
[18:47:02][D][binary_sensor:034]: 'Fr�
[18:47:02] ets Jan  8 2013,rst cause:4, boot mode:(3,6)
[18:47:02]
[18:47:02]wdt reset
[18:47:02]load 0x4010f000, len 3424, room 16 
[18:47:02]tail 0
[18:47:02]chksum 0x2e
[18:47:02]load 0x3fff20b8, len 40, room 8 
[18:47:02]tail 0
[18:47:02]chksum 0x2b
[18:47:02]csum 0x2b
[18:47:02]v000798d0
[18:47:02]~ld`
```
does that 10 times then gives up.. I've cut down my yaml file .. to the basics just to get it going, it looks like this:
```
substitutions:
  name: esphome-web-e1ab17
  friendly_name: ESPHome Web e1ab17
  # panelId: DSCAlarm  #used as the service variable name.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

# Example configuration entry
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.6.163
    gateway: 192.168.6.1
    subnet: 255.255.255.0

# wifi:
#   # Set up a wifi access point
#   ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

dsc_alarm_panel:
  # id: $panelId
  # #you can enter a list of user codes mapped to their names for display in armed/disarmed event messages
  # usercodes: "1:Jin" #
  
  #used to select the default partition associated with the alarm panel messages
  defaultpartition: "1" 
  
  maxzones: "32" # maximum amount of zones your system supports
  
  # dsc debug level: 0 = off, 1 = minimal, 2 = all packets shown on console  3 =  + serial port debugging
  dscdebuglevel: "2"  

  #ESP8266 Pins
  dscclockpin: "1"
  dscreadpin: "8"
  dscwritepin: "2" 
  
  clean_build: "false" #default is false.  set to true if getting duplication errors in linking step.  

#location of alarm panel code.  You can use the github release version  or 
#copy the code to directory "my_components" in your main esphome directory   
# see here for more info: https://esphome.io/components/external_components       
external_components:
  - source: github://Dilbert66/esphome-components@main
    components: [dsc_alarm_panel,binary_sensor,text_sensor] 
    refresh: 10min  

################################################################################
# Edit binary and text sensors below to suit your alarm setup. 
# The id code is entered using the "id_code:" tag.  Alternatively you can
# add the id code in round brackets  at the end of the sensor name: eg. (z1)
# You can safely add or remove any sensors as needed.

binary_sensor:
### zone setup ###
# zone status open/close for each zone 
# zone id code = z+zone number  
  - platform: template
    id_code: z1
    name: "Front door (z1)"
    device_class: door
    publish_initial_state: true     

text_sensor:
# general system status online/disconnected 
# system status id code = ss
  - platform: template
    id_code: ss  
    name: "System Status (ss)"
    icon: "mdi:shield"

```

how can I debug this 🙃
