### DISCUSSION TITLE
How to use as remote keypad?

### DISCUSSION THREAD

**Discussion by abishur** [Dilbert66/esphome-dsckeybus#53] [Q&A] [answered]
I was able to get this installed on my ESP32 and have it connected to my dsc PC1616.  I have it connected to home assistant.  

I want to use the programming within the PC1616 and only use the ESP32 as a means to send keypresses as if the home assistant device was nothing more than a remote keypad.  I'm thinking I can accomplish this by adding this to my homeassistant configuration.yaml file.

```
      arm_custom:
        - service: esphome.security_panel_alarm_keypress
          data_template:
            keys: '{{code}}'
```

Am I on the right track here?  Or am I supposed to hard code the keypress values into the keys parameter?
