### DISCUSSION TITLE
How to arm/disarm with esphome ?

### DISCUSSION THREAD

**Discussion by chreggy** [Dilbert66/esphome-dsckeybus#64] [Q&A] [answered]
Hello,

I want to connect a tag reader on an ESP32 GPIO to arm/disarm my dsc alarm. I spent a lot of time to understand how but I don't find.

Can you give me the right syntax with this example ?

```
  - platform: gpio
    name: "$systemName Tag Reader"
    id: tag_reader
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
    on_press:
      if:
        condition:
          - binary_sensor.is_on: rdy
          - binary_sensor.is_on: arm
```

Thanks :o)
