### ISSUE TITLE
Problem with sending time - wrong month

### ISSUE THREAD

**Issue by chreggy** [Dilbert66/esphome-dsckeybus#65]
Hello,

I have a problem with sending time, the month and time are wrong. 

```
time:
 - platform: sntp
   id: sntp_time
   timezone: "Europe/Paris"
   servers:
     - 134.214.100.6
```

`[20:11:22][D][text_sensor:067]: 'dscalarm event': Sending state '2022.00.09 18:11 P:1 Disarmed: Master code:40'`

Is there a problem in my config ?

Thanks.
